### ISSUE TITLE
can I compile it for Python 2.7

### ISSUE THREAD

**Issue by veso266** [Vaypron/ChromaPy#6]
Hi for some SDR Program I need python 2.7 and I am using windows and for some reason python 3 doesn't work alongside python2 so I wonder can I compile ChromaPy for using it with Python2.7?

Thanks for Anwsering and Best Regards

**Comment by tngebauer** [comment]
Haven't tested that yet, but it should be working. 
Just clone the repository, load it into Visual Studio and make sure that you include the /include and /libs directories of your Python-Installation in the project-file. If you need any further assistance feel free to ask.

**Comment by veso266** [comment]
Hi I've tried building it using Visual Studio 2012 (after changing toolset version to 4 I got theese errors
`1>------ Build started: Project: ChromaPy, Configuration: Release x64 ------
1>  ChromaSDK.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>ChromaSDK.cpp(168): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(168): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(176): error C2039: 'Mousepad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(176): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(184): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(184): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(193): error C2039: 'Keypad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(193): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(210): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(210): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(221): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(221): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(232): error C2039: 'Mousepad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(232): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(244): error C2039: 'Keypad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(244): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(257): error C2039: 'Headset_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(257): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(267): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(270): error C2039: 'Mousepad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(273): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(276): error C2039: 'Keypad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(279): error C2039: 'Headset_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(297): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(297): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(304): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(304): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(313): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(313): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(320): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(320): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(328): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(328): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(335): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(335): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(344): error C2039: 'Keyboard_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(344): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(353): error C2039: 'Keypad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(353): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(362): error C2039: 'Mouse_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(362): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(370): error C2039: 'Mousepad_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(370): error C2228: left of '.Color' must have class/struct/union
1>ChromaSDK.cpp(377): error C2039: 'Headset_Effect' : is not a member of 'Chroma_Implementation'
1>          c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\Header\ChromaSDK.h(37) : see declaration of 'Chroma_Implementation'
1>ChromaSDK.cpp(377): error C2228: left of '.Color' must have class/struct/union
1>  Headset.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>  Keyboard.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>  Keypad.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>  Mouse.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>  Mousepad.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>  Source.cpp
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(41): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(42): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(43): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(44): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2059: syntax error : '{'
1>c:\users\mitja\downloads\visual studio\compile that\chromapy-vanilla-master\chromapy-vanilla-master\chromapy\header\ChromaSDK.h(45): error C2334: unexpected token(s) preceding '{'; skipping apparent function body
1>Source.cpp(81): error C2552: 'ChromaPy' : non-aggregates cannot be initialized with initializer list
1>          'PyModuleDef' : Types with user defined constructors are not aggregate
1>Source.cpp(82): error C2065: 'PyModuleDef_HEAD_INIT' : undeclared identifier
1>Source.cpp(97): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(102): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(107): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(113): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(118): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(121): error C3861: 'PyModule_Create': identifier not found
1>Source.cpp(123): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
1>Source.cpp(142): error C2562: 'PyInit_ChromaPy' : 'void' function returning a value
1>          Source.cpp(91) : see declaration of 'PyInit_ChromaPy'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

so I am not sure what I am doing wrong I've also included python include and libs dirs
![error pnh](https://user-images.githubusercontent.com/6347325/27971552-60f8c17c-6353-11e7-820f-8340d7f7b944.png)

Thanks for Anwsering and Best Regards

**Comment by tngebauer** [comment]
Try to add the /include and the /libs directory in the VC++Directories tab as seen in the picture below. 

![Screenshot](https://i.gyazo.com/8d73ab8adbe2be8886fe9afc3d290d4b.png "Sceenshot")

Also, I can't tell you if there are problems with the vanilla repo. I can only help you with the main repo :)

**Comment by veso266** [comment]
I did as you suggested and now I am getting a difrent error
`1>------ Build started: Project: ChromaPy, Configuration: Release x64 ------
1>  ChromaSDK.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Headset.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Keyboard.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Keypad.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Mouse.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Mousepad.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Smart Home.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Source.cpp
1>c:\python27\include\pyconfig.h(68): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
1>  Yeelight.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\SFML 64bit\include\SFML/System/Err.hpp(32): fatal error C1083: Cannot open include file: 'ostream': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`
BTW: I wwitched to your repo now

**Comment by tngebauer** [comment]
Hm, ok. Let me see if I can recreate your error. Otherwise I'm gonna compile it for you :) 
Do you use Python 32 or 64bit?


Edit: I don't get any problems compiling it for Python 2.7 with Visual Studio 2017.

**Comment by veso266** [comment]
hmm weird I am using Python 2.7 64Bit

after doing this: 
![visualbasic](https://user-images.githubusercontent.com/6347325/27984712-f53bbb62-63dc-11e7-9327-b9bc911f149f.png)

I resolved previus error but I get a difrent one now: 
`1>------ Build started: Project: ChromaPy, Configuration: Release x64 ------
1>  ChromaSDK.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Headset.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Keyboard.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Keypad.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Mouse.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Mousepad.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Smart Home.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Source.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
1>  Yeelight.cpp
1>C:\Users\Mitja\Downloads\Visual Studio\Compile That\ChromaPy-master\ChromaPy-master\ChromaPy\3rd Party\nlohmann\json.hpp(44): fatal error C1083: Cannot open include file: 'initializer_list': No such file or directory
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

and after reading online I discovered that its Visual Studio 2012 error so I can't fix it 
do you think you could compile it for me? (Python 2.7 64 Bit)

Thanks for Anwsering and Best Regards

**Comment by tngebauer** [comment]
According to multiple test, I can confirm, that ChromaPy can't be compiled for Python 2.7.
