### ISSUE TITLE
[Python 2.7] Compilation error: 'PyInit_ChromaPy': 'void' function returning a value

### ISSUE THREAD

**Issue by RedFantom** [Vaypron/ChromaPy#7]
For my own [python-rgb-keyboards](https://github.com/RedFantom/python-rgb-keyboards) repository, I am looking to compile this project for at least Python 2.7, 3.5 and 3.6 to be able to offer Razer support in the library. I have looked at using `ctypes.cdll` (as I have also done for other brands) in order to work with the Chroma SDK directly, but this is no option given the complicated way the Razer library works and my C++ is not nearly good enough to make that work with Python.

Now, the actual issue is that compiling for Python 3.5 and 3.6 works fine, but when I want to compile for 2.7 (specifically 2.7.13, both x86 and x86-64), I get the following errors:

```
1>Source.cpp(88): error C2065: 'PyModuleDef_HEAD_INIT': undeclared identifier
1>Source.cpp(94): error C2027: use of undefined type 'PyModuleDef'
1>Source.cpp(87): note: see declaration of 'PyModuleDef'
1>Source.cpp(103): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(108): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(113): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(119): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(124): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(127): error C3861: 'PyModule_Create': identifier not found
1>Source.cpp(129): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(135): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
1>Source.cpp(156): error C2562: 'PyInit_ChromaPy': 'void' function returning a value
1>Source.cpp(97): note: see declaration of 'PyInit_ChromaPy'
```
To me this seems like the code is actually incompatible with Python 2.7. While this may seem so, I don't think this issue is related to issue #6 .

I am compiling on the following environment:

```
Visual Studio 2017 Community
Windows 7 64-bit
Build configurations for Python 2.7, 3.5, 3.6 (all for both x86 and x86-64)

**Comment by tngebauer** [comment]
Hm, I'm gonna investigate on that problem. 
Meanwhile you may want to take a look at the [ChromaPython](https://github.com/chroma-sdk/chroma-python) project. It's a library completely written in python and working with the new Rest API. It's still in development, but should already work fine :)

**Comment by RedFantom** [comment]
While that does look like an interesting project, and I will certainly take a detailed look later, I'd prefer if the users of the library would not have to do anything but copying over the DLL-files (as they are under proprietary software licenses), so I don't think that ChromaPython will be a real option.

**Comment by tngebauer** [comment]
I don't actually get your point. It's doing the same with the Rest API, what ChromaPy is doing with the DLL.
The Rest API is officially created by Razer and according to them it should be the way to go for further projects. It also works on every device, because it's builtin into Razer Synapse. So the user wouldn't even have to copy anything to use your library with Razer devices.

**Comment by RedFantom** [comment]
But as far as I understand it, one has to either compile and install the [chroma-core](https://github.com/chroma-sdk/chroma-core) or install the Razer Synapse software. This would make the library dependent on not only a third-party DLL-file, but on a third-party program. It is also my understanding (and I may be wrong as I have no prior experience with C++ Python extensions) that with ChromaPy the generated .pyd files are actually all that is required to communicate with the keyboard, and thus would not introduce this dependency. If adding Razer support is not possible without Razer software, then I will not add Razer support to the library, for the reasons that it would make the software harder to use, more difficult to test and I cannot understand such a design decision on Razer's part nor support it.

**Comment by tngebauer** [comment]
I'm sorry to disappoint you, but the .pyd is just a wrapper for Razers Chroma DLL. Their DLL is proprietary and only comes with the installation of Razers own Synapse Software.

**Comment by RedFantom** [comment]
Oh, I see. If they had provided the DLL separately I would have been fine with it, but in that case I will be dropping the idea of Razer support for now. I don't want an open-source library to depend on a closed ecosystem. Thank you for helping me out. I will leave this issue open for you, and if you have any questions to me about the issue, feel free to ask 😄
