### ISSUE TITLE
Colour Enum

### ISSUE THREAD

**Issue by DeflatedPickle** [Vaypron/ChromaPy#8]
It'd be nice to have an Enum for colours in the library, so scriptwriters don't have to keep defining them. Written either in C++ or Python - I don't know which would be easier to make work.

A use sample:
```python
import ChromaPy

keyboard = ChromaPy.Keyboard()
keyboard.setColor(ChromaPy.Colours.BLUE)
```

An implementation sample (in Python):
```python
from enum import Enum

class Colours(Enum):
    RED = (255,0,0)
    BLUE = (255,0,0)
    GREEN = (0,255,0)
```

**Comment by tngebauer** [comment]
My development in ChromaPy is currently on hold. Please use ChromaPython for future projects.
